### PR TITLE
Visualization

### PR DESCRIPTION
**Pull request by arora767287**
I tested this with random numbers and it worked (so then I modified it to work with the MCU class), but I'm not entirely sure that it works with the MCUInterface methods for getting measurements.

### CODE REVIEW

**Comment by fillnye** [comment]
Hmm, was PyQt3D even a option for this task?

**Comment by arora767287** [comment]
That does seem like a better idea. I just used VPython because it's very very easy to use, but I'm not sure that it can be put in a widget on the interface since it always opens up in a browser window.

**Comment by fillnye** [comment]
Yah using what you are comfortable with is a higher priority. Even though it being on a separate window may not be the ideal solution using PyQt3D might be more annoying then using vpython.

**Comment by lutetjeff** [comment]
We will work on a proper visualization software next R&D season (next week)

**Pull request closed without merging**
